introduction:
  - "&5&lHej [player]"
  - "&8* &7Välkommen till &d&lNTIGymnasiet Umeå&7s Minecraft server."
  - "[newline]"
  - "&5&lInformation"
  - "&8* &7Samma regler gäller här som i vår Discord server."
  - "&8* &7Du kan inte spela under lektions tid."